import telebot
import emoji
bot = telebot.TeleBot('5053914266:AAHFfbvmqjwsuPwqkr0Lkq0erBhrIX_4_wI')

from telebot import types

@bot.message_handler(content_types=['text'])
def get_text_messages(message):
  if message.text == "/start":
      bot.send_sticker(message.chat.id, "CAACAgIAAxkBAAEDh4dhwOmxBgb70cktrFdrGdNLztPswQACIAADwZxgDGWWbaHi0krRIwQ")
      bot.send_message(message.from_user.id, "Привіт! Я допоможу тобі знайти корисні додатки у потрібній тобі сфері.")
      keyboard = types.InlineKeyboardMarkup()
      key_trevel = types.InlineKeyboardButton(text=emoji.emojize(":airplane:")+' Подорожі '+ emoji.emojize(":airplane:"), callback_data='1')
      keyboard.add(key_trevel)
      key_finance = types.InlineKeyboardButton(text=emoji.emojize(":bar_chart:")+' Фінанси '+emoji.emojize(":bar_chart:"), callback_data='2')
      keyboard.add(key_finance)
      key_bank = types.InlineKeyboardButton(text=emoji.emojize(":money_with_wings:")+' Банківські маніпуляції '+emoji.emojize(":money_with_wings:"), callback_data='3')
      keyboard.add(key_bank)
      key_drive = types.InlineKeyboardButton(text=emoji.emojize(":automobile:")+' Для водіїв '+emoji.emojize(":automobile:"), callback_data='4')
      keyboard.add(key_drive)
      key_state = types.InlineKeyboardButton(text=emoji.emojize(":open_book:")+' Державні програми '+emoji.emojize(":open_book:"), callback_data='5')
      keyboard.add(key_state)
      key_hels = types.InlineKeyboardButton(text=emoji.emojize(":pill:")+" Здоров'я "+emoji.emojize(":pill:"), callback_data='6')
      keyboard.add(key_hels)
      key_mobile = types.InlineKeyboardButton(text=emoji.emojize(":mobile_phone:")+' Мобільні оператори '+emoji.emojize(":mobile_phone:"), callback_data='7')
      keyboard.add(key_mobile)      
      bot.send_message(message.from_user.id, text='Обери сферу:', reply_markup=keyboard)
  elif message.text == "/help":
      bot.send_message(message.from_user.id, "Напишіть /start та слідуйте за вказанням.")
  else:
      bot.send_sticker(message.chat.id, "CAACAgIAAxkBAAEDh5FhwOtzhxOsA7NO2hRa8S5lHXFBhAACJAADwZxgDEgkWrolDSiOIwQ")
      bot.send_message(message.from_user.id, "Я не розумію. Напишіть /help.")

@bot.callback_query_handler(func=lambda call: True)
def callback_worker(call):
    if call.data == "1":
        bot.send_message(chat_id=call.message.chat.id, text=emoji.emojize(":airplane:")+"[Foursquare](https://play.google.com/store/apps/details?id=com.joelapenna.foursquared&hl=ru&gl=US) \n\rТут зібрані всі, навіть найновіші або менш популярні місця будь-якого міста. Найрізноманітніші точки: від вокзалів до хостелів, від набережних до університетів та шкіл, від парків до пралень, пляжі, острови, нічні клуби та інше. \n\r\n\r "+emoji.emojize(":airplane:")+"[BlaBlaCar](https://play.google.com/store/apps/dev?id=6206618813943963783&hl=ru&gl=US) \n\rCистема для пошуку попутників, що подорожують машиною. Інакше кажучи, сервіс, який дозволяє водіям скоротити витрати на проїзд між містами, а пасажирам/або попутникам — дешево і вчасно дістатися пункту призначення, особливо коли на літаки чи поїзди не залишилося квитків. \n\r\n\r "+ emoji.emojize(":airplane:")+"[Triposo](https://www.triposo.com/) \n\rТут і англо-український розмовник, і історія країни різними мовами, обмін валюти, карти всіх великих (і не дуже) міст України. Список готелів, ресторанів, кафе, парків, музеїв, театрів у кожному з міст, із зазначенням цін. Адреси лікарень, відділень банку, поліції, інформація про транспортну систему міста. Прогноз погоди у будь-якому місті України. \n\r\n\r "+ emoji.emojize(":airplane:")+"[EasyWay](https://play.google.com/store/apps/details?id=com.eway&hl=ru&gl=US) \n\rУ пару кліків воно становить маршрут вашого пересування на громадському транспорті з пункту А до пункту Б, при цьому вибираючи найбюджетніший або найшвидший варіант. Тут же вказано час роботи метро, ​​тролейбуса, електрички, трамвая та автобуса в залежності від маршруту. Але головний бонус – це можливість через GPS стежити, як далеко від зупинки потрібний вам автобус чи тролейбус. \n\r\n\r "+ emoji.emojize(":airplane:")+"[iWC (WC-Київ)](https://play.google.com/store/apps/details?id=com.iwc.fax.android&hl=ru&gl=US) \n\rДодаток, яке за допомогою GPS-навігації визначає ваше місцезнаходження та відображає на карті найближчі до вас місця, де можна справити потребу. Карта покаже, як до них пройти, час роботи, також вартість, якщо така стягується. Діє програма у великих містах України.)\n\r", parse_mode='Markdown') 
    elif call.data == "2":
        bot.send_message(chat_id=call.message.chat.id, text=emoji.emojize(":bar_chart:")+"[Monefy](https://play.google.com/store/apps/details?id=com.monefy.app.lite&hl=ru&gl=US) \n\rОдна з найкращих програм для ведення домашньої бухгалтерії. Є можливість вести єдиний бюджет кількома користувачами, мультивалютність, систему обліку виплат за кредитами, смарт-бюджет для економії. \n\r\n\r "+ emoji.emojize(":bar_chart:")+"[Фінанси](https://play.google.com/store/apps/details?id=ru.innim.my_finance&hl=ru&gl=US) \n\rКористувач може персоналізувати програму, тобто запровадити власні категорії витрат. є безліч інструментів для наочного відображення фінансових потоків. Працює з різними валютами, а також є органайзером кредитних виплат. \n\r\n\r "+ emoji.emojize(":bar_chart:")+"[CoinKeeper](https://play.google.com/store/apps/details?id=com.disrapp.coinkeeper.material&hl=ru&gl=US) \n\rМожна отримувати повідомлення від банків, вести доходи і витрати, ставити цілі та контролювати їх досягнення, вести облік по всій сім'ї та кожному її представнику одночасно, зберігати знижкові картки в одному додатку (NFS), виводити інформацію в таблиці CVS.\n\r", parse_mode='Markdown') 
    elif call.data == "3":
        bot.send_message(chat_id=call.message.chat.id, text=emoji.emojize(":money_with_wings:")+"[Монобанк](https://play.google.com/store/apps/details?id=com.ftband.mono&hl=ru&gl=US) \n\rЦе найпопулярніший банк і його дійсно люблять багато користувачів. \n\r\n\r "+ emoji.emojize(":money_with_wings:")+"[Приват24](https://play.google.com/store/apps/details?id=ua.privatbank.ap24&hl=ru&gl=US) \n\rНомер 1 в Україні за кількістю користувачів, його програма знаходиться на 7 місці в загальному топі мобільного софту від TNS Ukraine. \n\r\n\r "+ emoji.emojize(":money_with_wings:")+"[Ощад 24/7](https://play.google.com/store/apps/details?id=ua.oschadbank.online&hl=ru&gl=US) \n\rХороші відгуки користувачів та практична зручність роботи. Додаток Ощад 24/7 на даний момент дуже надійний і функціональний. \n\r\n\r "+ emoji.emojize(":money_with_wings:")+"[Альфа Банк](https://play.google.com/store/apps/details?id=ru.alfabank.mobile.android&hl=ru&gl=US) \n\rOдним із перших реалізував моментальний випуск віртуальних карток з можливістю отримання пластикової в будь-якому відділенні банку. \n\r\n\r "+ emoji.emojize(":money_with_wings:")+"[ПУМБ Online](https://play.google.com/store/apps/details?id=com.fuib.android.spot.online&hl=ru&gl=US) \n\rКористувач програми може отримувати у Viber повну інформацію про стан своїх рахунків. Ще одна вдала знахідка банку – конструктор депозитів. \n\r\n\r "+ emoji.emojize(":money_with_wings:")+"[UKRSIB online](https://play.google.com/store/apps/details?id=com.ukrsibbank.client.android&hl=ru&gl=US) \n\rПишається своїм вбудованим у мобільний додаток планувальником доходів та витрат. \n\r\n\r "+ emoji.emojize(":money_with_wings:")+"[Raiffeisen Online](https://play.google.com/store/apps/details?id=ua.aval.dbo.client.android&hl=ru&gl=US) \n\rНайбільш відвідуваний банківський веб-ресурс України.\n\r", parse_mode='Markdown') 
    elif call.data == "4":
        bot.send_message(chat_id=call.message.chat.id, text=emoji.emojize(":automobile:")+"[Штрафи правил дорожнього руху](https://play.google.com/store/apps/details?id=com.shtrafua.android.shtrafua&hl=ru&gl=US) \n\rОсновна мета – оперативно повідомляти водіїв про нові штрафи за ігнорування правил дорожнього руху. \n\r\n\r "+ emoji.emojize(":automobile:")+"[MAPS.ME](https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro&hl=ru&gl=US) \n\rЗ автономними картами водій почуватиметься комфортно навіть на краю світу. Пошук маршруту та GPS-навігація працює без Wi-Fi. \n\r\n\r "+ emoji.emojize(":automobile:")+"[Waze](https://play.google.com/store/apps/details?id=com.waze&hl=ru&gl=US) \n\rНавігатор по місту, що працює у реальному часі. Додаток побудує не тільки потрібний маршрут, але й розповість користувачеві про пробки, ремонтні роботи, поліцію, ДТП та інші події. \n\r\n\r "+ emoji.emojize(":automobile:")+"[INRIX ParkMe](https://play.google.com/store/apps/details?id=com.parkme.consumer&hl=ru&gl=US) \n\rДодаток для безболісного паркування. За допомогою карти людина легко визначить розташування недорогої стоянки. \n\r\n\r "+ emoji.emojize(":automobile:")+"[Страхування та допомога в дорозі](https://play.google.com/store/apps/details?id=io.opencomm.experience.cefcorewards&hl=ru&gl=US) \n\rПрограма від агрегатора страхових продуктів. Це своєрідний гаманець для страхових договорів. У ньому можна: оформити ОСАЦВ та інші види страховок без посередників від топових гравців ринку, зберігати поліс, отримувати повідомлення про закінчення терміну договору. \n\r\n\r "+ emoji.emojize(":automobile:")+"[TOPLYVO UA](https://play.google.com/store/apps/details?id=ua.fuel&hl=ru&gl=US) \n\rУ програмі можна купувати талони на паливо з фіксованою знижкою.\n\r", parse_mode='Markdown') 
    elif call.data == "5":
        bot.send_message(chat_id=call.message.chat.id, text=emoji.emojize(":open_book:")+"[Дія](https://play.google.com/store/apps/details?id=ua.gov.diia.app&hl=ru&gl=US) \n\rЄдиний портал державних послуг. Онлайн відкриття ФОП, оформлення допомоги при народженні дитини або пенсії, отримання ліцензій та дозволів.\n\r\n\r "+ emoji.emojize(":open_book:")+"[Вдома](https://play.google.com/store/apps/details?id=ua.gov.diia.quarantine&hl=ru&gl=US) \n\rПристосування для запобігання поширенню COVID-19 в Україні.\n\r\n\r "+ emoji.emojize(":open_book:")+"[Вулик](https://vulyk.gov.ua/) \n\rРозроблено в рамках проекту спільно з Державним агентством з питань електронного урядування для центрів надання адміністративних послуг. \n\r\n\r "+ emoji.emojize(":open_book:")+"[Соціальна громада](https://socgromada.ioc.gov.ua/) \n\rЦе клієнт-серверне WEB-приложение, яке розроблене з метою наближення адміністративних послуг соціального характеру до мешканців територіальних громад.\n\r", parse_mode='Markdown')
    elif call.data == "6":
        bot.send_message(chat_id=call.message.chat.id, text=emoji.emojize(":pill:")+"[HELSI](https://play.google.com/store/apps/details?id=helsi.me&hl=ru&gl=US) \n\rСервіс запису до лікарів та зберігання медичних даних. \n\r\n\r "+ emoji.emojize(":pill:")+"[Tabletki.ua](https://play.google.com/store/apps/details?id=com.tabletkiua.tabletki&hl=ru&gl=US) \n\rЗнайдіть потрібні ліки, порівняйте ціни в аптеках та забронюйте зі знижкою.\n\r", parse_mode='Markdown')
    elif call.data == "7":
        bot.send_message(chat_id=call.message.chat.id, text="Виберіть посилання щодо свого мобільного оператора: \n\r"+ emoji.emojize(":mobile_phone:")+"[Мій Київстар](https://play.google.com/store/apps/details?id=com.kyivstar.mykyivstar&hl=ru&gl=US) \n\r\n\r "+ emoji.emojize(":mobile_phone:")+"[My Vodafone](https://play.google.com/store/apps/details?id=qa.vodafone.myvodafone&hl=ru&gl=US) \n\r\n\r "+ emoji.emojize(":mobile_phone:")+"[Мій lifecell](https://play.google.com/store/apps/details?id=com.life.my&hl=ru&gl=US)\n\r", parse_mode='Markdown')
    
bot.polling(none_stop=True, interval=0)
